<?php

$addresses = array(
	'36-26 Main St. 2X <br />Flushing NY 11354',
	'265 Canal St, #401<br />New York, NY 10013',
	'6402 8th Ave, #220<br />Brooklyn NY 11220',
	'1-718-886-4008<br />1-917-822-4139',
);

$location_links = array(
	'schedule-page.php',
	'schedule-page.php',
	'schedule-page.php',
	'contact-page.php',
);

$location_titles = array(
	'en' => array(
		'Flushing School',
		'Chinatown',
		'Brooklyn',
		'Contact Us',
	),
	'zh-hans' => array(
		'法拉盛分校',
		'唐人街分校',
		'布碌崙分校',
		'來電垂詢',
	),
);

$page_links = array(
	'en' => array(
		'About',
		'Hiring',
		'Mission',
		'News',
		'Teachers',
		'Log In',
		'Schedule',
		'Contact',
		'Gallery',
		'',
	),
	'zh-hans' => array(
		'學校簡介',
		'教師招聘',
		'教育目標',
		'學校新聞',
		'我們的老師',
		'學生登錄',
		'課程註冊',
		'聯絡網頁',
		'藝術畫廊',
		'',
	),
);