<?php

$school_names = array(
	'法拉盛地址:',
	'唐人街地址:',
	'布鲁克林:',
	'Email:',
);

$school_address = array(
	'36-26 Main St. 2X<br>Flushing, NY, 11354<br><br>联系电话:<br>718-886-4008<br>917-822-4139<br>917-417-8014',
	'265 Canal St,<br>#401, New York<br>NY, 10013',
	'64-02 8th Ave,<br>#220, Brooklyn,<br>NY, 11220',
	'rybart54<br>@gmail.com<br><br>',
);

$post_it_color = array(
	'postItBig.png',
	'postItRed.png',
	'postItPurple.png',
	'postItLime.png',
);