<?php

$addresses = array(
	'136-18 39Ave, 9FL<br />Flushing NY 11354',
	'83-25Broadway,#3F<br />Elmhurst NY 11373',
	'1-718-886-4008<br />1-917-822-4139',
	'6402 8th Ave, #220<br />Brooklyn NY 11220',
	'265 Canal St, #401<br />New York, NY 10013',
);

$location_links = array(
	'school-flushing',
	'school-elmhurst',
	'contact-page',
	'school-brooklyn',
	'school-chinatown',
);

$location_titles = array(
	'en' => array(
		'Flushing School',
		'Elmhurst School',
		'Contact Us',
		'Brooklyn',
		'Chinatown',
	),
	'zh-hans' => array(
		'法拉盛分校',
		'艾姆赫斯特',
		'來電垂詢',
		'布碌崙分校',
		'唐人街分校',
	),
);