<?php

$header_links = array(
		'school-info',
		'registration-info',
		'student-login',
		'art-gallery',
		'contact-page',
		'teacher-hiring',
);

$header_titles = array(
	'en' => array(
		'School Information Page',
		'Registration Information Page',
		'Student Login Page',
		'Art Gallery Page',
		'Contact Page',
		'Teacher Hiring Page',
	),
	'zh-hans' => array(	
		'學校簡介',
		'報名信息',
		'學生登錄',
		'藝術畫廊',
		'聯絡網頁',
		'教師招聘',
	),
);

