<?php

$box_images = array(
	'images/Home Page Img Folder/missionBlockImg.png',
	'images/Home Page Img Folder/applyBlockImg.png',
	'images/Home Page Img Folder/visitBlockImg.png',
	'images/Home Page Img Folder/teacherBlockImg.png',
);

$boxes_links = array(
	'en' => array(
		'Mission',
		'Schedule',
		'Visit Us',
		'Teachers',
	),
	'zh-hans' => array(
		'報名信息',
		'課程时间',
		'參觀學校',
		'學校老師',
	),
);

$news = array(
	'en' => array(
		'School News'
	),
	'zh-hans' => array(
		'學校新聞',
	),
);

$bottom_title = array(
	'en' => array(
		'Study    -   Grow    -    Create'
	),
	'zh-hans' => array(
		'學習    -    啟發     -    創作',
	),
);

$bottom_images = array(
	'images/Home Page Img Folder/mainPagePicCircle1.png',
	'images/Home Page Img Folder/mainPagePicCircle2.png',
	'images/Home Page Img Folder/mainPagePicCircle3.png',
);

$bottom_text = array(
	'en' => array(
		'Stories',
		'History',
		'Creativity',
	),
	'zh-hans' => array(
		'學生故事',
		'學校歷史',
		'藝術創意',
	),
);

$moblie_homepage_info = array(
	'title' => array(
		'en' => array(
			'Registration',
			'Schedule',
			'Our Teachers',
			'Visit Us',
		),
		'zh-hans' => array(
			'報名信息',
			'課程时间',
			'學校老師',
			'參觀學校',
		),
	),
	'top' => array(
		'en' => array(
			'15 Class per Semester',
			'Flushing School',
			'Traditional trained',
			'Queens Chinatown',
		),
		'zh-hans' => array(
			'每學期十五節課',
			'法拉盛學校',
			'傳統繪畫技巧',
			'美東華人社區',
		),
	),
	'mid' => array(
		'en' => array(
			'School provides',
			'Multiple Time slots',
			'Applies',
			'Flushing Address',
		),
		'zh-hans' => array(
			'學校提供',
			'上課時間',
			'培養興趣',
			'法拉盛校址',
		),
	),
	'bot' => array(
		'en' => array(
			'All material',
			'Each class',
			'Small group classrooms',
			'136-18  39Ave 9FL',
		),
		'zh-hans' => array(
			'所有教材',
			'每課為一小時',
			'小班制個別指',
			'136-18  39Ave 9FL',
		),
	),
	'end' => array(
		'en' => array(
			'Pencils, paint, paper',
			'One hour and half',
			'Teaching method',
			'Flushing, NY, 11354'
		),
		'zh-hans' => array(
			'材料及畫冊',
			'三十分鐘',
			'導教學法',
			'Flushing, NY, 11354'
		),
	),
	'page-style' => array(
		'colors' => array(
			'ryb-red',
			'ryb-orange',
			'ryb-dark-blue',
			'ryb-purple',
		),
		'images' => array(
			'images/mobile Img Folder/mobile-registraion-circle.png',
			'images/mobile Img Folder/mobile-hours-circle.png',
			'images/mobile Img Folder/mobile-staff-circle.png',
			'images/mobile Img Folder/mobile-location-circle.png',
		),
	),
);
