<?php

$box_images = array(
	'images/Home Page Img Folder/missionBlockImg.png',
	'images/Home Page Img Folder/applyBlockImg.png',
	'images/Home Page Img Folder/visitBlockImg.png',
	'images/Home Page Img Folder/teacherBlockImg.png',
);

$boxes_links = array(
	'en' => array(
		'Mission',
		'Schedule',
		'Visit Us',
		'Teachers',
	),
	'zh-hans' => array(
		'教育目標',
		'課程时间',
		'參觀學校',
		'學校老師',
	),
);

$news = array(
	'en' => array(
		'School News'
	),
	'zh-hans' => array(
		'學校新聞',
	),
);

$bottom_title = array(
	'en' => array(
		'Study    -   Grow    -    Create'
	),
	'zh-hans' => array(
		'學習    -    啟發     -    創作',
	),
);

$bottom_images = array(
	'images/Home Page Img Folder/mainPagePicCircle1.png',
	'images/Home Page Img Folder/mainPagePicCircle2.png',
	'images/Home Page Img Folder/mainPagePicCircle3.png',
);

$bottom_text = array(
	'en' => array(
		'Stories',
		'History',
		'Creativity',
	),
	'zh-hans' => array(
		'學生故事',
		'學校歷史',
		'藝術創意',
	),
);