<?php

$box_images = array(
	'missionBlockImg.png',
	'applyBlockImg.png',
	'visitBlockImg.png',
	'teacherBlockImg.png',
);

$boxes_links = array(
	'en' => array(
		'Mission',
		'Schedule',
		'Visit Us',
		'Teachers',
	),
	'zh-hans' => array(
		'報名信息',
		'課程时间',
		'參觀學校',
		'學校老師',
	),
);

$news = array(
	'en' => array(
		'School News'
	),
	'zh-hans' => array(
		'學校新聞',
	),
);

$bottom_title = array(
	'en' => array(
		'Study    -   Grow    -    Create'
	),
	'zh-hans' => array(
		'學習    -    啟發     -    創作',
	),
);

$bottom_images = array(
	'mainPagePicCircle1.png',
	'mainPagePicCircle2.png',
	'mainPagePicCircle3.png',
);

$bottom_text = array(
	'en' => array(
		'Stories',
		'History',
		'Creativity',
	),
	'zh-hans' => array(
		'學生故事',
		'學校歷史',
		'藝術創意',
	),
);

$test_teaser = array(
	'en' => array(
		'Red, yellow, blue art school art schools since its inception fifteen years to draw attention to basic ...',
		'Red, yellow, blue art school in 2014 fall semester curriculum content is now available. Teaching class ...',
		'Composition and proportion and easiest modeling capabilities, learn to use a variety of art materials ...',
	),
	'zh-hans' => array(
		'藝術名校紅黃藍美術學校自創辦十五年來以重視繪畫基本功训练享譽美東華人社區。該校自創辦以來就有一整套完整的基本功訓練和 ...',
		'紅黃藍美術學校 2014 年秋季班教学课程内容现推出。教學類容分六個部分。第一部分是兒童畫；這是針對4至7歲的小朋友，主要 ...',
		'構圖和比例及最简单的造型能力，学会使用各种美术材料和美术用具，学会画面中个体的表现和多种物体的表现，学会与美术老师 ...',
	),
	'colors' => array(
		'ryb-red',
		'ryb-dark-yellow',
		'ryb-dark-blue',
	),
);

$moblie_homepage_info = array(
	'title' => array(
		'en' => array(
			'Registration',
			'Schedule',
			'Our Teachers',
			'Visit Us',
			'School News',
		),
		'zh-hans' => array(
			'報名信息',
			'課程时间',
			'學校老師',
			'參觀學校',
			'學校新聞',
		),
	),
	'top' => array(
		'en' => array(
			'15 Class per Semester',
			'Flushing School',
			'Traditional trained',
			'Queens Chinatown',
		),
		'zh-hans' => array(
			'每學期十五節課',
			'法拉盛學校',
			'傳統繪畫技巧',
			'美東華人社區',
		),
	),
	'mid' => array(
		'en' => array(
			'School provides',
			'Multiple Time slots',
			'Applies',
			'Flushing Address',
		),
		'zh-hans' => array(
			'學校提供',
			'上課時間',
			'培養興趣',
			'法拉盛校址',
		),
	),
	'bot' => array(
		'en' => array(
			'All material',
			'Each class',
			'Small group classrooms',
			'136-18  39Ave 9FL',
		),
		'zh-hans' => array(
			'所有教材',
			'每課為一小時',
			'小班制個別指',
			'136-18  39Ave 9FL',
		),
	),
	'end' => array(
		'en' => array(
			'Pencils, paint, paper',
			'One hour and half',
			'Teaching method',
			'Flushing, NY, 11354'
		),
		'zh-hans' => array(
			'材料及畫冊',
			'三十分鐘',
			'導教學法',
			'Flushing, NY, 11354'
		),
	),
	'page-style' => array(
		'colors' => array(
			'ryb-red',
			'ryb-orange',
			'ryb-dark-blue',
			'ryb-purple',
		),
		'images' => array(
			'mobile-registraion-circle.png',
			'mobile-hours-circle.png',
			'mobile-staff-circle.png',
			'mobile-location-circle.png',
		),
	),
);
