<?php

$registration_button = array(
	'RegButton01.png',
	'RegButton02.png',
	'RegButton03.png',
	'RegButton04.png',
	'RegButton05.png',
);

$registration_icon = array(
	'RegIcon01.png',
	'RegIcon02.png',
	'RegIcon03.png',
	'RegIcon04.png',
	'RegIcon05.png',
);

$registration_flat = array(
	'RegFlat01.png',
	'RegFlat02.png',
	'RegFlat03.png',
	'RegFlat04.png',
	'RegFlat05.png',
);

$registration_text = array(
	'en' => array(
		'',
		'',
		'',
		'',
		'',
	),
	'zh-hans' => array(
		'学生通过
		电话预约
		欢迎疑问
			
		点击这看
		聯繫信息',
		'',
		'',
		'',
		'',
	),
);