<?php

$one_line_addresses = array(
	'36-26 Main St. 2X, 9FL, Flushing NY 11354',
	'83-25 Broadway,#3F, Elmhurst NY 11373',
	'6402 8th Ave, #220, Brooklyn NY 11220',
	'265 Canal St, #401, New York, NY 10013',
);

$school_names = array(
	'en' => array(
		'Flushing School',
		'Elmhurst School',
		'Brooklyn',
		'Chinatown',
	),
	'zh-hans' => array(
		'法拉盛',
		'艾姆赫斯特',
		'布碌崙',
		'唐人街',
	),
);

$table_header  = array(
	'en' => array(
		'Thursday',
		'Friday',
		'Saturday',
		'Sunday',
	),
	'zh-hans' => array(
		'星期四',
		'星期五',
		'星期六',
		'星期天',
	),
);

$time_slots = array(
	'9:30AM - 11:00AM',
	'11:00AM - 12:30PM',
	'1:00PM - 2:30PM',
	'2:30PM - 4:00PM',
	'4:00PM - 5:30PM',
	'5:30PM - 7:00PM',
);

$flushing_time_slot = array(
	'Thursday' => array(
		'',
		'',
		'',
		'T',
		'T',
		'T',
	),
	'Friday' => array(
		'',
		'',
		'',
		'',
		'',
		'',
	),
	'Saturday' => array(
		'T',
		'T',
		'T',
		'T',
		'T',
		'T',
		'',
	),
	'Sunday' => array(
		'T',
		'T',
		'T',
		'T',
		'T',
		'T',
		'',
	),
);
