<?php

#Website Constent Var
define('SITE_NAME', 'RYB');
define('TITLE_MARKUP', '<div class="h1 ryb-purple color-title"><span class="ryb-red">紅</span><span class="ryb-blue">黃</span><span class="ryb-yellow">藍</span>美術學校</div>');
define('TITLE_MARKUP_EN', '<div class="h1 ryb-purple color-title"><span class="ryb-red">R.</span><span class="ryb-blue">Y.</span><span class="ryb-yellow">B.</span>ART</div>');
define('TITLE_MOBILE', '<div class="spacing-reset"><span class="h1 ryb-red">紅</span><span class="h1 ryb-blue">藍</span><span class="h1 ryb-yellow">黃</span><span class="h1 ryb-purple">美術學校</span>');

$language = 'zh-hans';
$language = 'en';