<?php

$registration_button = array(
	'RegButton01.png',
	'RegButton02.png',
	'RegButton03.png',
	'RegButton04.png',
	'RegButton05.png',
);

$registration_icon = array(
	'RegIcon01.png',
	'RegIcon02.png',
	'RegIcon03.png',
	'RegIcon04.png',
	'RegIcon05.png',
);

$registration_flat = array(
	'RegFlat01.png',
	'RegFlat02.png',
	'RegFlat03.png',
	'RegFlat04.png',
	'RegFlat05.png',
);

$registration_text = array(
	'en' => array(
		'',
		'',
		'',
		'',
		'',
	),
	'zh-hans' => array(
		'学生通过<br />电话预约<br />欢迎疑问<br /><br />点击这看<br />聯繫信息',
		'檢查適合<br />您的時間<br />来校参观<br /><br />点击这看<br />時間地址',
		'免费试课<br />学校提供<br />美术工具<br /><br />点击这看<br />教育方法',
		'了解学生<br />绘画程度<br />提供評測<br /><br />点击这看<br />课程内容',
		'通过试课<br />决定是否<br />前来学习<br /><br />点击这看<br />课程学费',
	),
);

$registration_color = array(
	'ryb-pink',
	'ryb-yolk',
	'ryb-sky-blue',
	'ryb-purple',
	'ryb-grass-green',
);